part1: part1.cpp
	g++ -std=c++11 -o part1 part1.cpp -Wall -Wextra -pedantic
	./part1 < test.txt
	./part1 < input.txt

part2: part2.cpp
	g++ -std=c++11 -o part2 part2.cpp -Wall -Wextra -pedantic
	./part2 < test.txt
	./part2 < input.txt

clean:
	rm -f part1 part2
